---
version: v1
workspaces:
  - name: vault-production
    environment: production
    terraform:
      version: "1.5.7"
    working_directory: "infrastructure/environments/production"
    vcs_provider:
      trigger_prefixes:
        - "infrastructure/environments/production/"
        - "infrastructure/modules/"
    auto_apply: false
    run_triggers:
      always_trigger: false
    hooks:
      pre_plan:
        - name: "Validate Terraform Configuration"
          commands:
            - "terraform fmt -check=true -diff"
            - "terraform validate"
      post_plan:
        - name: "Security Scan"
          commands:
            - "echo 'Security scan placeholder - integrate with your \
              security tools'"
    tags:
      - vault
      - production
      - infrastructure
      - proxmox
