all:
  children:
    jumpbox_vm:
      hosts:
        "{{ jumpbox_hostname }}":
          ansible_host: "{{ jumpbox_ip_home }}"
    k8s_nodes:
      children:
        masters:
          hosts:
            master-1:
              ansible_host: "{{ cluster_nodes.masters[0].ip }}"
            master-2:
              ansible_host: "{{ cluster_nodes.masters[1].ip }}"
        workers:
          hosts:
            worker-1:
              ansible_host: "{{ cluster_nodes.workers[0].ip }}"
            worker-2:
              ansible_host: "{{ cluster_nodes.workers[1].ip }}"
            worker-3:
              ansible_host: "{{ cluster_nodes.workers[2].ip }}"
      vars:
        # SSH proxy configuration for cluster nodes (excluding jumpbox from proxying itself)
        ansible_ssh_common_args: "-o ProxyJump={{ ansible_user }}@{{ jumpbox_ip_home }} -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes"
