#cloud-config
ssh_pwauth: false
timezone: America/New_York
users:
- name: ansible
  gecos: Ansible User
  groups: users,admin,wheel
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa5HX4EzWRRY+YhC979KqYtBPLvTOXtriwzql1uTthp
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL8lJBJBcFUTLgZ9eRx0c/XZau4NxVAdDm1sXMlMd1vL
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKls14HDdv2r2QIhGQfEluBmzrGI2cxjwtdkAWrc4ZRr
packages:
  - qemu-guest-agent
  - net-tools
  - curl
package_update: true
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "done" > /opt/.cloud-config.done