# Ansible Variables for Supernova-MicroK8s-Infra
# These variables define network configuration and hostnames used throughout the playbooks

# Network Configuration
home_network_gateway: "192.168.1.1"
cluster_network_gateway: "192.168.3.1"
# Host Configuration
jumpbox_hostname: "jumpbox"
jumpbox_ip_home: "192.168.1.240"
jumpbox_ip_cluster: "192.168.3.250"
# Cluster Node Configuration
cluster_nodes:
  masters:
    - name: "master-1"
      ip: "192.168.3.11"
    - name: "master-2"
      ip: "192.168.3.12"
  workers:
    - name: "worker-1"
      ip: "192.168.3.21"
    - name: "worker-2"
      ip: "192.168.3.22"
    - name: "worker-3"
      ip: "192.168.3.23"
# Service Configuration
rancher_hostname: "rancher.ansible"
argocd_hostname: "argocd.ansible"
# SSH Configuration
ansible_user: "ansible"
ssh_proxy_host: "{{ jumpbox_hostname }}"
ssh_proxy_ip: "{{ jumpbox_ip_home }}"
