#cloud-config
# =============================================================================
# = Custom Cloud-Init User-Data Configuration =================================
# =============================================================================
# This is an example cloud-init user-data file that will be applied to the
# template. When VMs are cloned from this template, this configuration will
# be executed on first boot.
#
# Copy this file to 'user-data.yaml' and customize it for your needs.
#
# Cloud-Init Documentation: https://cloudinit.readthedocs.io/

# =============================================================================
# = User Configuration ========================================================
# =============================================================================

# Create default user with sudo privileges
ssh_pwauth: false
timezone: America/New_York
users:
- name: ansible
  gecos: Ansible User
  groups: users,admin,wheel
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa5HX4EzWRRY+YhC979KqYtBPLvTOXtriwzql1uTthp
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL8lJBJBcFUTLgZ9eRx0c/XZau4NxVAdDm1sXMlMd1vL
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKls14HDdv2r2QIhGQfEluBmzrGI2cxjwtdkAWrc4ZRr
package_upgrade: true
packages:
  - qemu-guest-agent
  - curl
  - wget
  - vim
  - git
  - htop
  - net-tools
  - ca-certificates
  - gnupg
  - lsb-release
runcmd:
  - [ systemctl, start, qemu-guest-agent ]

# =============================================================================
# = Hostname Configuration ====================================================
# =============================================================================

# Hostname will be set during clone, but you can provide a default
hostname: ubuntu-template
# Preserve hostname across reboots
preserve_hostname: false

# =============================================================================
# = System Configuration ======================================================
# =============================================================================

# Configure NTP
ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org

# =============================================================================
# = File System Configuration =================================================
# =============================================================================

# Resize root filesystem to use all available space
growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false

# =============================================================================
# = Custom Scripts ============================================================
# =============================================================================

# Run commands early in boot process (before network)
bootcmd:
  - echo 'Cloud-init boot starting...'

# =============================================================================
# = Write Files ===============================================================
# =============================================================================

write_files:
  # Example: Create a custom motd
  - path: /etc/motd
    content: |
      ======================================
      Ubuntu 24.04 LTS - Custom Template
      Deployed via Terraform + Cloud-Init
      ======================================
    permissions: '0644'

  # Example: Custom script
  - path: /usr/local/bin/custom-script.sh
    content: |
      #!/bin/bash
      echo "Custom script executed at $(date)"
    permissions: '0755'

# =============================================================================
# = Power Management ==========================================================
# =============================================================================

# Reboot after cloud-init completes (optional)
# power_state:
#   mode: reboot
#   message: Rebooting after cloud-init configuration
#   timeout: 30
#   condition: true

# =============================================================================
# = Final Message =============================================================
# =============================================================================

final_message: |
  Cloud-init configuration completed!
  System is ready for use.
  Uptime: $UPTIME
  Timestamp: $TIMESTAMP
